<a href="https://colab.research.google.com/github/robinsonm2021/Data_science/blob/main/Robinson_Stats_2022_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [1]:
import numpy as np

In [2]:
from IPython.core.display import display, HTML

In [3]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

#####Comment: To get a specific range of numbers use the formula below you could also name the numbers in the range.

In [78]:
for i in range(100):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [79]:
for i in range(5,8):
    print(i)

5
6
7


In [80]:
for i in range(3):
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

#####Comment: For root functions use the equations below. you could also add to those root equations by adding the variable in this case x to any number.

In [7]:
def square(x):
    return x**2

In [8]:
square(5)

25

In [9]:
square(square(2))

16

In [10]:
square(square(square(2)))


256

In [11]:
square(123456)

15241383936

In [12]:
square(square(5))

625

In [13]:
def add_two(x):
    return x+2

In [14]:
add_two(5)

7

In [15]:
square(add_two(5))

49

### Logical Branching

#####Comment: To create a choice problem use the formula below. You can also add messages into the function.

In [16]:
choice = "apple"

In [17]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [18]:
choice = "orange"

In [19]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [20]:
choice = "apple"

In [21]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

#####Comment: Use the function below to create user input 

In [22]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): apple


In [23]:
choice

'apple'

In [24]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose apples.


#### Coins

#####Comment: for random numbers, true or false questions or coin flips use the functions below.

In [25]:
np.random.random()

0.15645792969367278

In [26]:
np.random.random() > 0.5

True

In [27]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [28]:
flip_coin()

Heads


### Graphics Output

#####Comment: to display a message or a photo use the functions below you can also use them for ranges of coins and an actual coin flip.

In [29]:
display(HTML('<h1>Hello, world!</h1>'))

In [30]:
def coin():
  return np.random.randint(2)

In [31]:
coin()

1

In [32]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))

In [33]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [34]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [35]:
show_img(heads)

In [36]:
show_img(tails)

In [37]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [38]:
flip_coin()

In [39]:
for i in range(5):
    flip_coin()

In [40]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

#####Comment: for a card range use the function below

In [41]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [42]:
a = np.arange(52)

In [43]:
shuffle(a)

array([13, 45, 22, 48, 44, 18, 39, 26, 20,  9,  8, 21, 32, 28, 36, 10, 11,
       17, 23, 33, 24, 42, 46,  1, 37,  2, 47, 38, 30, 40,  4,  6,  3, 25,
        7,  5, 49, 29, 14, 41, 19, 43, 51, 50, 27, 15,  0, 16, 35, 12, 31,
       34])

In [44]:
np.random.permutation(52)

array([ 3,  8, 49, 17, 42, 41, 21, 34, 51, 38, 14, 10, 33,  7, 15, 44, 16,
       26, 19, 35, 18, 12,  0, 43, 22,  6, 45, 24, 29, 37, 39, 28, 47,  9,
        2, 32, 23, 50, 40,  1,  5,  4, 13, 46, 31, 20, 36, 48, 30, 25, 11,
       27])

### Speed Test

#####Comment: Use the functions below to shuffle cards, select random cards, or to find the speed of the shuffle. It also shows photos of cards and the way to choose a specific card and suit.

In [45]:
%%timeit
shuffle(a)

186 µs ± 16.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [46]:
%%timeit
np.random.permutation(52)

3.66 µs ± 219 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [47]:
np.random.permutation(52)

array([19, 49,  7, 15,  0, 13, 20, 26, 35, 32, 41,  2,  8, 38, 31, 12,  6,
       36, 45, 33, 34, 24,  4, 28, 10, 42, 44,  1, 18, 51, 43, 21, 37, 27,
       40, 46, 50, 14, 48, 25, 29,  3, 16,  5, 22,  9, 17, 23, 47, 39, 30,
       11])

In [48]:
cards = np.random.permutation(52)

In [49]:
cards

array([14, 28, 33, 29, 20, 45, 44, 35, 27, 32,  7, 40, 30, 15, 46, 39, 37,
        2, 50, 11,  1, 41,  5, 17, 31,  4, 36, 43, 42, 23, 24, 38, 48, 18,
       21, 10, 16, 12,  8, 49, 26,  3, 22, 47, 13, 51,  0, 25, 34,  9, 19,
        6])

In [50]:
cards[0]

14

In [51]:
cards[1]

28

In [52]:
cards[2]

33

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [53]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [54]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [55]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [56]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [57]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [58]:
card_name(0)

'Ace of Clubs'

In [59]:
card_name(51)

'King of Diamonds'

In [60]:
cards = np.random.permutation(52)

In [61]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [62]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Jack of Diamonds', 'Six of Spades', 'Eight of Diamonds')

In [63]:
for i in range(5):
    print(card_name(cards[i]))

Jack of Diamonds
Six of Spades
Queen of Spades
Ten of Diamonds
Nine of Spades


In [64]:
for i in range(15):
    print(card_name(cards[i]))

Jack of Diamonds
Six of Spades
Queen of Spades
Ten of Diamonds
Nine of Spades
Ace of Diamonds
King of Spades
King of Diamonds
Five of Hearts
Eight of Spades
Ace of Hearts
Two of Clubs
Eight of Clubs
Ten of Clubs
Jack of Spades


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [65]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [66]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [67]:
i = np.random.randint(4)
j = np.random.randint(13)

In [68]:
i,j

(1, 2)

In [69]:
suit[i]

'p'

In [70]:
card[j]

'3'

In [71]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [72]:
show_img(img)

In [73]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [74]:
card_image(3)

'k4'

In [75]:
img = card_url_head + card_image(3) + card_url_tail

In [76]:
show_img(img)

In [77]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)